# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.17.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.17.0
        cache: 'npm'
        cache-dependency-path: ./mouse-frontend-app/package-lock.json
    - run: |
        cd ./mouse-frontend-app
        npm ci
    - run: |
        cd ./mouse-frontend-app
        npm run build --if-present   
    - name: Run ESLint
      #run: |
        #cd ./mouse-frontend-app
        #npx eslint .
      uses: stefanoeb/eslint-action@1.0.2
      continue-on-error: false
        
    - name: Fail if any previous step failed
      if: ${{ failure() }}
      run: |
        echo "An error occurred during the build process. Aborting push."
        exit 1
